name: 'Build and Push Image'

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'prepare/get_downloader.sh'
      - 'src/*'
      - 'Dockerfile'
    
  workflow_dispatch:
    inputs:
      push:
        description: 'Push to GHCR'
        required: false
        type: boolean
        default: 'false'

permissions:
  contents: read
  packages: write

jobs:   
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Prepare (Get downloader)'
        run: |
          chmod +x ./prepare/get_downloader.sh
          ./prepare/get_downloader.sh

      - name: 'Log in to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push image (linux/amd64)'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: './Dockerfile'
          platforms: 'linux/amd64'
          push: ${{ github.event.inputs.push }}
          tags: |
            ghcr.io/${{ github.repository }}:linux-amd64-${{ github.sha }}
            ghcr.io/${{ github.repository }}:linux-amd64-latest
    
