name: 'Test Dockerfile'

on:
  push:
    branches: 
      - 'main'

jobs:
  test-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Build Docker image'
        run: |
          docker buildx build -t docker-hytale-server .

      - name: Run Docker container
        run: |
          docker run --rm docker-hytale-server
