name: 'Test Dockerfile'

on:
  push:
    branches: 
      - 'main'

  workflow_dispatch: {}

jobs:
  test-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Prepare (Get downloader)'
        run: |
          ./prepare/get_downloader.sh

      - name: 'Build Docker image'
        run: |
          docker buildx build -t docker-hytale-server .

      - name: Run Docker container
        timeout-minutes: 1
        run: |
          docker run --rm docker-hytale-server
